spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_URL}/tmpp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
server:
  port: 8080
logging:
  level: debug
  level.top: debug
mybatis:
  type-aliases-package: top.sl.tmpp.common.entity,top.sl.tmpp.common.pojo
  mapper-locations: classpath:mappers/*.xml
cas:
  enabled: true
  debug: true
  server-url: http://login.greathiit.com
  login-url: http://login.greathiit.com/login
  logout-url: http://login.greathiit.com/logout
  login-success-url: http://localhost:8081
  local-server-url: http://localhost:8080