spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
server:
  port: 8080
mybatis:
  type-aliases-package: top.sl.tmpp.common.entity,top.sl.tmpp.common.pojo
  mapper-locations: classpath:mappers/*.xml
cas:
  enabled: true
  debug: true
  server-url: http://login.greathiit.com
  login-url: http://login.greathiit.com/login
  logout-url: http://login.greathiit.com/logout