spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_URL}/tmpp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC&allowPublicKeyRetrieval=true
logging:
  level: debug
  level.top: debug
cas:
  login-success-url: http://localhost:8081
  local-server-url: http://localhost:8080