spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_URL}/tmpp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
logging:
  level: debug
  level.top: debug
mybatis:
  type-aliases-package: top.sl.tmpp.common.entity
  mapper-locations: classpath:mappers/*.xml
